<a href="https://colab.research.google.com/github/l642/irsi_data_classification_using_SVM/blob/main/svm_hyper_para.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
data=pd.read_csv('/content/Iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  ...  PetalWidthCm         Species target
0      1            5.1           3.5  ...           0.2     Iris-setosa      0
1      2            4.9           3.0  ...           0.2     Iris-setosa      0
2      3            4.7           3.2  ...           0.2     Iris-setosa      0
3      4            4.6           3.1  ...           0.2     Iris-setosa      0
4      5            5.0           3.6  ...           0.2     Iris-setosa      0
..   ...            ...           ...  ...           ...             ...    ...
145  146            6.7           3.0  ...           2.3  Iris-virginica      2
146  147            6.3           2.5  ...           1.9  Iris-virginica      2
147  148            6.5           3.0  ...           2.0  Iris-virginica      2
148  149            6.2           3.4  ...           2.3  Iris-virginica      2
149  150            5.9           3.0  ...           1.8  Iris-virginica      2

[150 rows x 7 columns]

In [5]:
data1=data.drop(['Id','Species'],axis=1)
data1

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  target
0              5.1           3.5            1.4           0.2       0
1              4.9           3.0            1.4           0.2       0
2              4.7           3.2            1.3           0.2       0
3              4.6           3.1            1.5           0.2       0
4              5.0           3.6            1.4           0.2       0
..             ...           ...            ...           ...     ...
145            6.7           3.0            5.2           2.3       2
146            6.3           2.5            5.0           1.9       2
147            6.5           3.0            5.2           2.0       2
148            6.2           3.4            5.4           2.3       2
149            5.9           3.0            5.1           1.8       2

[150 rows x 5 columns]

In [6]:
x=data1.drop('target',axis=1)
x

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [8]:
y=data['target']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [9]:
from sklearn.preprocessing import StandardScaler
scaling=StandardScaler()
x=scaling.fit_transform(x)
x

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [11]:
x=pd.DataFrame(x)
x

0         1         2         3
0   -0.900681  1.032057 -1.341272 -1.312977
1   -1.143017 -0.124958 -1.341272 -1.312977
2   -1.385353  0.337848 -1.398138 -1.312977
3   -1.506521  0.106445 -1.284407 -1.312977
4   -1.021849  1.263460 -1.341272 -1.312977
..        ...       ...       ...       ...
145  1.038005 -0.124958  0.819624  1.447956
146  0.553333 -1.281972  0.705893  0.922064
147  0.795669 -0.124958  0.819624  1.053537
148  0.432165  0.800654  0.933356  1.447956
149  0.068662 -0.124958  0.762759  0.790591

[150 rows x 4 columns]

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


In [13]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
y_predict=model.predict(x_test)
y_predict

array([0, 1, 1, 1, 0, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 1, 0,
       2, 0, 2, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 2, 1, 2, 0, 0, 2, 1, 2, 2,
       1])

In [19]:
from sklearn.metrics import accuracy_score
print(model.score(x_train,y_train))
print(model.score(x_test,y_test))

0.9809523809523809
0.9555555555555556


In [46]:
from sklearn.metrics import confusion_matrix
z=confusion_matrix(y_predict,y_test)
z

array([[14,  0,  0],
       [ 0, 10,  1],
       [ 0,  1, 19]])

In [29]:
model1=SVC(kernel='rbf',C=10,gamma='auto')
model1.fit(x_train,y_train)
print(model1.score(x_train,y_train))
print(model1.score(x_test,y_test))

0.9619047619047619
0.9777777777777777


In [31]:
model11=SVC(kernel='rbf',C=30,gamma='scale')
model11.fit(x_train,y_train)
print(model11.score(x_train,y_train))
print(model11.score(x_test,y_test))

0.9809523809523809
0.9333333333333333


In [23]:
model2=SVC(kernel='poly')
model2.fit(x_train,y_train)
print(model2.score(x_train,y_train))
print(model2.score(x_test,y_test))

0.9333333333333333
0.9333333333333333


In [24]:
model2=SVC(kernel='linear')
model2.fit(x_train,y_train)
print(model2.score(x_train,y_train))
print(model2.score(x_test,y_test))

0.9809523809523809
0.9777777777777777


In [36]:
from sklearn import svm
model5=svm.SVC(kernel='rbf',C=30,gamma='auto')
model5.fit(x_train,y_train)

SVC(C=30, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [39]:
print(model5.score(x_train,y_train))
print(model5.score(x_test,y_test))

0.9809523809523809
0.9333333333333333


In [41]:
# corss validation score
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),x_train,y_train,cv=5)

array([0.95238095, 0.85714286, 0.95238095, 0.95238095, 1.        ])

In [48]:
 #corss validation score
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='rbf',C=100,gamma='auto'),x_train,y_train,cv=5)

array([0.95238095, 0.85714286, 0.95238095, 0.9047619 , 1.        ])

In [49]:
#corss validation score
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='poly',C=100,gamma='auto'),x_train,y_train,cv=5)

array([0.9047619 , 0.9047619 , 0.9047619 , 0.95238095, 1.        ])

In [57]:
# using for loop
import numpy as np
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),x_train,y_train, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)


avg_scores

{'linear_1': 0.9619047619047618,
 'linear_10': 0.9523809523809523,
 'linear_20': 0.9523809523809523,
 'rbf_1': 0.9428571428571428,
 'rbf_10': 0.9428571428571428,
 'rbf_20': 0.9523809523809523}

In [59]:
#grid search CV
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)
clf.fit(x_train,y_train)
clf.cv_results_

{'mean_fit_time': array([0.00192733, 0.00137291, 0.00153189, 0.00135837, 0.0014256 ,
        0.00137553]),
 'mean_score_time': array([0.0008707 , 0.00081716, 0.00085864, 0.00079136, 0.00083442,
        0.00078626]),
 'mean_test_score': array([0.94285714, 0.96190476, 0.94285714, 0.95238095, 0.95238095,
        0.95238095]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'rank_test_score': array([5, 1, 5, 2, 2, 2], dtype=int32),
 'split0_test_score': array([0.9047619 , 0.95

In [60]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001927      0.000588  ...        0.046657                5
1       0.001373      0.000043  ...        0.055533                1
2       0.001532      0.000078  ...        0.046657                5
3       0.001358      0.000030  ...        0.042592                2
4       0.001426      0.000025  ...        0.052164                2
5       0.001376      0.000026  ...        0.042592                2

[6 rows x 15 columns]

In [61]:
df[['param_C','param_kernel','mean_test_score']]



param_C param_kernel  mean_test_score
0       1          rbf         0.942857
1       1       linear         0.961905
2      10          rbf         0.942857
3      10       linear         0.952381
4      20          rbf         0.952381
5      20       linear         0.952381

In [62]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [63]:
clf.best_score_

0.9619047619047618

In [71]:
# RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(x_train,y_train)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)
rs.fit(x_train,y_train)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      20          rbf         0.952381
1       1       linear         0.961905

In [72]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=6
)
rs.fit(x_train,y_train)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.942857
1       1       linear         0.961905
2      10          rbf         0.942857
3      10       linear         0.952381
4      20          rbf         0.952381
5      20       linear         0.952381

In [74]:
rs.best_score_

0.9619047619047618

In [75]:
rs.best_params_

{'C': 1, 'kernel': 'linear'}

In [78]:
# so finally fitting SVM model with best parameters
model6=SVC(kernel='linear',C=1)
model6.fit(x_train,y_train)
print(model6.score(x_train,y_train))
print(model6.score(x_test,y_test))

0.9809523809523809
0.9777777777777777
